### ISSUE TITLE
Payment Due Date View Model

### ISSUE THREAD

**Issue by rachellefontanilla** [LideLinusZhang/cs446-project#24]

**Comment by LideLinusZhang** [comment]
How to use hilt DI to create view models
1. https://developer.android.com/training/dependency-injection/hilt-jetpack#compose
2. https://developer.android.com/develop/ui/compose/libraries#hilt-navigation

How to use StateFlow in view models
1. https://developer.android.com/kotlin/flow/stateflow-and-sharedflow
